### ISSUE TITLE
Marketing site todo's

### ISSUE THREAD

**Issue by pmarsceill** [josh/Aware#25]
- [x] Create a switch to show dark menubar example.
- [x] Write a little JS that makes the clock accurate to system time.
- [x] Write a little JS that will start the Aware timer on page load
- [x] Add Google Analytics tracking 618dae31c8d5891e6417c3d3a8badbb9a219dbbc

**Comment by josh** [comment]
Assigned, I'm on these!
